vscode:
  extensions:
    - alexkrechik.cucumberautocomplete
    - codezombiech.gitignore
    - redhat.java@1.22.1
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - anwar.papyrus-pdf